### PR TITLE
Raster Chapters

### PR DESCRIPTION
**Pull request by schao333**
Initial commit of raster chapters:

- Raster math
- Rasterize
- Replace values
- Window operations

### CODE REVIEW

**Comment by mmann1123** [comment]
Thanks I just finished my review.

**Review by mmann1123 — APPROVED** [review]

**Review by mmann1123 — APPROVED** [review]

**Review by mmann1123 — CHANGES_REQUESTED** [review]
Still looking for a description of the kernel you generate here. Or maybe updateing it to the mean kernel or something similar.

**Comment by schao333** [comment]
Thanks for your feedback, Mike! Please see revised versions for changes.

**Comment by mmann1123** [comment]
Thanks I will take a look soon

**Review by mmann1123 — APPROVED** [review]

**Pull request merged**
